[package]
name = "gearify"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"

gears_core = { path = "../gears_core" }
wasmtime = "1.0"