[package]
name = "gears_core"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slotmap = "1.0"
thiserror = "1.0"
enum_dispatch = "0.3.7"