name: Rust

on:
  push:
    branches: [ egg ]
  pull_request:
    branches: [ egg ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Build gear_impls
      run: cargo build -p gear_impls --examples --target wasm32-wasi --release
    - name: Run tests
      run: cargo test --workspace --exclude gear_impls --verbose
    - name: Archive gears
      uses: actions/upload-artifact@v3
      with:
        name: gearify-test-gears
        path: gearify\tests\output
